version: '3'
services:
  app_conversor_distancia:
    build:
      context: ./conversao-distancia/
    ports:
      - "9191:5000"
  app_conversor_temperatura:
    build:
      context: ./conversao-temperatura/src/
    ports:
      - "9090:8080"
  app_conversor_peso:
    build:
      context: ./conversao-peso/ConversaoPeso.Web/
    ports:
      - "8080:80"
  