version: '3.8'

services:

  mongo:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_vol
    networks:
      - produto_net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - produto_net
    depends_on:
      - mongo
    volumes:
      - mongo_vol
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

volumes:
  mongo_vol:

networks:
  produto_net:
    driver: bridge
