version: '3.3'

services:

  db:
    image: mysql:5.7
    volumes:
      - wordpress_vol:/var/lib/mysql
    restart: always
    networks:
      - produto_wordpress_net
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    ports:
      - "8080:80"
    networks:
      - produto_wordpress_net

volumes:
  wordpress_vol:


networks:
  produto_wordpress_net:
    driver: bridge
